services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./scripts/docker-init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  pgdata:
