// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using OregonProviderFinder.Core.Data;

#nullable disable

namespace OregonProviderFinder.Core.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260927193946_LocationForeignKey")]
    partial class LocationForeignKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OregonProviderFinder.Core.Entities.City", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double>("Lng")
                        .HasColumnType("double precision")
                        .HasColumnName("lng");

                    b.Property<int>("ProviderCount")
                        .HasColumnType("integer")
                        .HasColumnName("provider_count");

                    b.HasKey("Name")
                        .HasName("pk_cities");

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("OregonProviderFinder.Core.Entities.ImportRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("DataAsOf")
                        .HasColumnType("date")
                        .HasColumnName("data_as_of");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<long>("RowsKept")
                        .HasColumnType("bigint")
                        .HasColumnName("rows_kept");

                    b.Property<long>("RowsScanned")
                        .HasColumnType("bigint")
                        .HasColumnName("rows_scanned");

                    b.Property<string>("SourceName")
                        .HasColumnType("text")
                        .HasColumnName("source_name");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_import_runs");

                    b.ToTable("import_runs", (string)null);
                });

            modelBuilder.Entity("OregonProviderFinder.Core.Entities.Provider", b =>
                {
                    b.Property<string>("Npi")
                        .HasMaxLength(10)
                        .HasColumnType("character(10)")
                        .HasColumnName("npi")
                        .IsFixedLength();

                    b.Property<string>("AddressLine1")
                        .HasColumnType("text")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text")
                        .HasColumnName("address_line2");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("CredentialText")
                        .HasColumnType("text")
                        .HasColumnName("credential_text");

                    b.PrimitiveCollection<string[]>("Credentials")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("credentials");

                    b.Property<DateOnly?>("EnumerationDate")
                        .HasColumnType("date")
                        .HasColumnName("enumeration_date");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.PrimitiveCollection<string[]>("GroupKeys")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("group_keys");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double?>("Lng")
                        .HasColumnType("double precision")
                        .HasColumnName("lng");

                    b.Property<string>("LocationPrecision")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("location_precision");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text")
                        .HasColumnName("middle_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("phone");

                    b.Property<string>("Prefix")
                        .HasColumnType("text")
                        .HasColumnName("prefix");

                    b.Property<string>("PrimaryTaxonomyCode")
                        .HasColumnType("text")
                        .HasColumnName("primary_taxonomy_code");

                    b.Property<DateOnly?>("RegistryLastUpdated")
                        .HasColumnType("date")
                        .HasColumnName("registry_last_updated");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("to_tsvector('english', coalesce(full_name, '') || ' ' || coalesce(city, '') || ' ' || coalesce(specialty_labels, ''))", true);

                    b.Property<string>("Sex")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("sex");

                    b.Property<string>("SpecialtyLabels")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("specialty_labels");

                    b.Property<string>("Suffix")
                        .HasColumnType("text")
                        .HasColumnName("suffix");

                    b.Property<string>("Zip5")
                        .HasMaxLength(5)
                        .HasColumnType("character(5)")
                        .HasColumnName("zip5")
                        .IsFixedLength();

                    b.HasKey("Npi")
                        .HasName("pk_providers");

                    b.HasIndex("City")
                        .HasDatabaseName("ix_providers_city");

                    b.HasIndex("Credentials")
                        .HasDatabaseName("ix_providers_credentials");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Credentials"), "gin");

                    b.HasIndex("FullName")
                        .HasDatabaseName("ix_providers_full_name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("FullName"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("FullName"), new[] { "gin_trgm_ops" });

                    b.HasIndex("GroupKeys")
                        .HasDatabaseName("ix_providers_group_keys");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("GroupKeys"), "gin");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_providers_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "gin");

                    b.HasIndex("SpecialtyLabels")
                        .HasDatabaseName("ix_providers_specialty_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SpecialtyLabels"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SpecialtyLabels"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Zip5")
                        .HasDatabaseName("ix_providers_zip5");

                    b.HasIndex("Lat", "Lng")
                        .HasDatabaseName("ix_providers_lat_lng");

                    b.ToTable("providers", (string)null);
                });

            modelBuilder.Entity("OregonProviderFinder.Core.Entities.ProviderLocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AddressLine1")
                        .HasColumnType("text")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text")
                        .HasColumnName("address_line2");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Npi")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character(10)")
                        .HasColumnName("npi")
                        .IsFixedLength();

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<string>("State")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_provider_locations");

                    b.HasIndex("Npi")
                        .HasDatabaseName("ix_provider_locations_npi");

                    b.ToTable("provider_locations", (string)null);
                });

            modelBuilder.Entity("OregonProviderFinder.Core.Entities.ProviderTaxonomy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("text")
                        .HasColumnName("license_number");

                    b.Property<string>("LicenseState")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("license_state");

                    b.Property<string>("Npi")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character(10)")
                        .HasColumnName("npi")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("pk_provider_taxonomies");

                    b.HasIndex("Code")
                        .HasDatabaseName("ix_provider_taxonomies_code");

                    b.HasIndex("Npi")
                        .HasDatabaseName("ix_provider_taxonomies_npi");

                    b.ToTable("provider_taxonomies", (string)null);
                });

            modelBuilder.Entity("OregonProviderFinder.Core.Entities.Taxonomy", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<string>("Classification")
                        .HasColumnType("text")
                        .HasColumnName("classification");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("GroupKey")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("group_key");

                    b.Property<string>("Specialization")
                        .HasColumnType("text")
                        .HasColumnName("specialization");

                    b.HasKey("Code")
                        .HasName("pk_taxonomies");

                    b.ToTable("taxonomies", (string)null);
                });

            modelBuilder.Entity("OregonProviderFinder.Core.Entities.ZipCentroid", b =>
                {
                    b.Property<string>("Zip5")
                        .HasMaxLength(5)
                        .HasColumnType("character(5)")
                        .HasColumnName("zip5")
                        .IsFixedLength();

                    b.Property<double>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double>("Lng")
                        .HasColumnType("double precision")
                        .HasColumnName("lng");

                    b.HasKey("Zip5")
                        .HasName("pk_zip_centroids");

                    b.ToTable("zip_centroids", (string)null);
                });

            modelBuilder.Entity("OregonProviderFinder.Core.Entities.ProviderLocation", b =>
                {
                    b.HasOne("OregonProviderFinder.Core.Entities.Provider", "Provider")
                        .WithMany("Locations")
                        .HasForeignKey("Npi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_provider_locations_providers_npi");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("OregonProviderFinder.Core.Entities.ProviderTaxonomy", b =>
                {
                    b.HasOne("OregonProviderFinder.Core.Entities.Provider", "Provider")
                        .WithMany("Taxonomies")
                        .HasForeignKey("Npi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_provider_taxonomies_providers_npi");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("OregonProviderFinder.Core.Entities.Provider", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("Taxonomies");
                });
#pragma warning restore 612, 618
        }
    }
}
